### ISSUE TITLE
Checklist for release

### ISSUE THREAD

**Issue by ericmj** [hexpm/diff#9]
## Required
* [x] Add rollbar (https://github.com/hexpm/diff/pull/4)
* [x] Add logster (see hexpm) (https://github.com/hexpm/diff/pull/13)
* [x] Add mix release (https://github.com/hexpm/diff/pull/10)
* [x] Dockerfile + google cloud build (see hexpm/cloudbuild.yaml) (https://github.com/hexpm/diff/pull/10)
* [x] Add CI (https://github.com/hexpm/diff/pull/11)
* [x] Add to https://github.com/hexpm/hexpm-ops (terraform and kubernetes)
  * [x] Staging (https://github.com/hexpm/hexpm-ops/pull/21)
  * [x] Prod
* [x] Add license

## Nice to have
* [x] More tests =)
* [x] Add package checksum to cache key (https://github.com/hexpm/diff/pull/14)
* [x] Replace hex_core's default HTTP client httpc with hackney or mint (https://github.com/hexpm/diff/pull/15)
* [x] Clean up default phoenix stuff (assets/) (https://github.com/hexpm/diff/pull/16)
* [x] ~Add about page~Add footer
* [x] Add hex branding (https://github.com/hexpm/diff/pull/19)
* [x] Review design
* [x] Add landing page for links from https://hex.pm, for example`/diff/:package` and `/diff/:package/:to` which shows the version selector for the given package

## After release
* [x] Link from https://hex.pm package pages
* [x] Deploy hexpm with above links
* [x] Blog post and announce

**Comment by ericmj** [comment]
We are live!
